version: '3.1'

volumes:
  mysql:
    driver: local

services:
  db:
    image: mysql:8.0.37
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
