version: '3.1'

services:
  activemq:
    image: apache/activemq-artemis
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    restart: always